apiVersion: skaffold/v4beta13
kind: Config


build:
  artifacts:
    - image: ai-orchestration
      context: ai-orchestration
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false    

  