apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-server

  template:
    metadata:
      labels:
        app: ai-server

    spec:
      containers:
        - name: ai-server
          image: ai-orchestration:latest

          ports:
            - containerPort: 3000
              name:  ai-server-port

          resources:
            requests:
              cpu: "250m"
              memory: "128M"
            limits:
              cpu: "500m"
              memory: "256M"
          env:
          - name: GOOGLE_GENAI_API_KEY
            valueFrom:
             secretKeyRef:
              name: ai-secret
              key: GOOGLE_GENAI_API_KEY

          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5